import React, { useState, useMemo, useEffect } from 'react';
import { ShoppingBag, CreditCard, LayoutDashboard, Flame, Wallet, CalendarRange } from 'lucide-react';
import DealHunter from './components/DealHunter';
import CardOptimizer from './components/CardOptimizer';
import MyCards from './components/MyCards';
import SpendingManager from './components/SpendingManager';
import ShoppingPlanner from './components/ShoppingPlanner';
import { Transaction, CardUsageStatus, FinancialEvent, ShoppingItem } from './types';
import { MY_CARDS } from './constants';

type Tab = 'dashboard' | 'deals' | 'cards' | 'calc' | 'history' | 'plan';

// Clean Slate: No initial transactions
const INITIAL_TRANSACTIONS: Transaction[] = [];

// Clean Slate: No initial financial events
const INITIAL_FINANCIAL_EVENTS: FinancialEvent[] = [];

const App: React.FC = () => {
  const [activeTab, setActiveTab] = useState<Tab>('dashboard');

  // Load from LocalStorage or use Default
  const [transactions, setTransactions] = useState<Transaction[]>(() => {
      const saved = localStorage.getItem('shopee_hunter_transactions');
      return saved ? JSON.parse(saved) : INITIAL_TRANSACTIONS;
  });

  const [financialEvents, setFinancialEvents] = useState<FinancialEvent[]>(() => {
      const saved = localStorage.getItem('shopee_hunter_events');
      return saved ? JSON.parse(saved) : INITIAL_FINANCIAL_EVENTS;
  });

  const [shoppingList, setShoppingList] = useState<ShoppingItem[]>(() => {
      const saved = localStorage.getItem('shopee_hunter_shopping_list');
      return saved ? JSON.parse(saved) : [];
  });

  const [currentAsset, setCurrentAsset] = useState<number>(() => {
      const saved = localStorage.getItem('shopee_hunter_asset');
      return saved ? Number(saved) : 0;
  });

  // Persist data whenever it changes
  useEffect(() => {
      localStorage.setItem('shopee_hunter_transactions', JSON.stringify(transactions));
  }, [transactions]);

  useEffect(() => {
      localStorage.setItem('shopee_hunter_events', JSON.stringify(financialEvents));
  }, [financialEvents]);

  useEffect(() => {
      localStorage.setItem('shopee_hunter_shopping_list', JSON.stringify(shoppingList));
  }, [shoppingList]);

  useEffect(() => {
      localStorage.setItem('shopee_hunter_asset', currentAsset.toString());
  }, [currentAsset]);


  // Calculate current card usage derived from transaction history
  const cardUsage: CardUsageStatus[] = useMemo(() => {
    return MY_CARDS.map(card => {
        const cardTx = transactions.filter(t => t.cardId === card.id);
        const totalSpent = cardTx.reduce((sum, t) => sum + t.amount, 0);
        const totalCashback = cardTx.reduce((sum, t) => sum + t.cashbackEarned, 0);
        const remainingCap = card.maxCashback > 0 ? Math.max(0, card.maxCashback - totalCashback) : Infinity;
        
        // Min Spend Logic
        const minSpend = card.minSpend || 0;
        const remainingMinSpend = Math.max(0, minSpend - totalSpent);
        const metMinSpend = totalSpent >= minSpend;

        return {
            cardId: card.id,
            totalSpent,
            totalCashback,
            remainingCap,
            minSpend,
            metMinSpend,
            remainingMinSpend
        };
    });
  }, [transactions]);

  // Dynamically generate Credit Card Bills based on Transactions
  const computedFinancialEvents = useMemo(() => {
      const bills: FinancialEvent[] = [];
      const now = new Date();
      const currentYear = now.getFullYear();
      const currentMonth = now.getMonth();

      MY_CARDS.forEach(card => {
          if (card.id === 'cash-debit' || !card.dueDate) return;

          // Sum un-paid transactions for this card
          // Note: In a real app, we'd check statement periods. 
          // Here we simplify: All existing transactions for a card = Debt that needs paying next due date.
          const cardTx = transactions.filter(t => t.cardId === card.id);
          const totalDebt = cardTx.reduce((sum, t) => sum + t.amount, 0);

          if (totalDebt > 0) {
              // Calculate next due date
              let billMonth = currentMonth;
              if (now.getDate() > card.dueDate) {
                  billMonth = currentMonth + 1;
              }
              const billDate = new Date(currentYear, billMonth, card.dueDate);
              
              bills.push({
                  id: `bill-${card.id}`,
                  title: `Thanh toán thẻ ${card.name}`,
                  amount: totalDebt,
                  date: billDate.toISOString().split('T')[0], // YYYY-MM-DD
                  type: 'expense',
                  isCompleted: false, // Computed bills are pending by default
                  isAutoGenerated: true
              });
          }
      });
      
      // Merge with manual events
      return [...financialEvents, ...bills];
  }, [transactions, financialEvents]);

  // Filter pending bills for the planner
  const pendingBills = useMemo(() => {
      return computedFinancialEvents.filter(e => e.type === 'expense' && !e.isCompleted && !e.isAutoGenerated); 
      // Note: We exclude auto-generated credit card bills from "purchase planning" to avoid double counting, 
      // but include manual bills like Electricity/Water.
  }, [computedFinancialEvents]);

  const handleAddTransaction = (newTx: Transaction) => {
      setTransactions([...transactions, newTx]);
      
      // Logic: If paying by Cash/Debit -> Deduct Asset immediately
      // If Credit Card -> Do nothing to asset (it goes to liability/bill)
      if (newTx.cardId === 'cash-debit') {
          setCurrentAsset(prev => prev - newTx.amount);
      }
  };

  const handleRemoveTransaction = (id: string) => {
      const tx = transactions.find(t => t.id === id);
      if (tx && tx.cardId === 'cash-debit') {
           // Refund if deleting a cash transaction
           setCurrentAsset(prev => prev + tx.amount);
      }
      setTransactions(prev => prev.filter(t => t.id !== id));
  };

  const handleEditTransaction = (updatedTx: Transaction) => {
      const oldTx = transactions.find(t => t.id === updatedTx.id);
      
      // Handle Asset updates if switching between Cash <-> Credit or changing Amount
      if (oldTx) {
          let assetChange = 0;
          
          // Reverse old transaction effect
          if (oldTx.cardId === 'cash-debit') {
              assetChange += oldTx.amount;
          }

          // Apply new transaction effect
          if (updatedTx.cardId === 'cash-debit') {
              assetChange -= updatedTx.amount;
          }

          if (assetChange !== 0) {
              setCurrentAsset(prev => prev + assetChange);
          }
      }

      setTransactions(prev => prev.map(t => t.id === updatedTx.id ? updatedTx : t));
  };

  const handleClearAllTransactions = () => {
      if (window.confirm('CẢNH BÁO: Bạn có chắc chắn muốn xóa TOÀN BỘ lịch sử chi tiêu không? Hành động này không thể hoàn tác.')) {
          // If clearing, strictly strictly speaking we should probably reset assets or warn user, 
          // but let's just clear the list for now.
          setTransactions([]);
      }
  };

  // Financial Event Handlers
  const handleAddEvent = (event: FinancialEvent) => {
      setFinancialEvents([...financialEvents, event]);
  };

  const handleRemoveEvent = (id: string) => {
      setFinancialEvents(prev => prev.filter(e => e.id !== id));
  };

  const handleToggleEvent = (id: string) => {
      // Only toggle manual events in state. 
      // For auto-generated bills, usually marking them complete means paying them off (reducing Asset),
      // which is a complex flow (Asset -> Credit Card Debt).
      // For simplicity, we just toggle manual events here.
      setFinancialEvents(prev => prev.map(e => e.id === id ? { ...e, isCompleted: !e.isCompleted } : e));
  };

  // Shopping Planner Handlers
  const handleAddItem = (item: ShoppingItem) => {
      setShoppingList([...shoppingList, item]);
  };

  const handleRemoveItem = (id: string) => {
      setShoppingList(prev => prev.filter(i => i.id !== id));
  };

  const handleToggleItem = (id: string) => {
      setShoppingList(prev => prev.map(i => i.id === id ? { ...i, isPurchased: !i.isPurchased } : i));
  };

  const renderContent = () => {
    switch (activeTab) {
      case 'dashboard':
        return (
          <div className="space-y-10">
            {/* SECTION 1: SPENDING MANAGER (PRIORITY) */}
            <section className="bg-white/50 p-1 rounded-3xl">
                <h2 className="text-2xl font-bold text-gray-800 mb-6 flex items-center gap-3">
                    <div className="bg-shopee p-2 rounded-xl text-white shadow-lg shadow-orange-200">
                        <Wallet className="w-6 h-6" />
                    </div>
                    Quản lý Chi tiêu & Hóa đơn
                </h2>
                {/* Full Width Layout for Spending Manager */}
                <SpendingManager 
                    transactions={transactions} 
                    onAddTransaction={handleAddTransaction} 
                    onRemoveTransaction={handleRemoveTransaction}
                    onEditTransaction={handleEditTransaction}
                    onClearAllTransactions={handleClearAllTransactions}
                    cardUsage={cardUsage}
                    financialEvents={computedFinancialEvents}
                    currentAsset={currentAsset}
                    onUpdateAsset={setCurrentAsset}
                    onAddEvent={handleAddEvent}
                    onRemoveEvent={handleRemoveEvent}
                    onToggleEvent={handleToggleEvent}
                />
            </section>

            <hr className="border-gray-200" />

            {/* SECTION 2: MY CARDS */}
            <section>
              <h2 className="text-xl font-bold text-gray-800 mb-4 flex items-center gap-2">
                 <CreditCard className="w-5 h-5 text-gray-500"/>
                 Tổng quan thẻ của bạn
              </h2>
              <MyCards />
            </section>

            {/* SECTION 3: TOOLS GRID */}
            <section className="grid grid-cols-1 lg:grid-cols-2 gap-8">
               <div>
                   <h2 className="text-xl font-bold text-gray-800 mb-4 flex items-center gap-2">
                       <ShoppingBag className="w-5 h-5 text-gray-500"/>
                       Máy tính Hoàn Tiền
                   </h2>
                   <CardOptimizer cardUsage={cardUsage} />
               </div>
               <div>
                   <h2 className="text-xl font-bold text-gray-800 mb-4 flex items-center gap-2">
                       <Flame className="w-5 h-5 text-gray-500"/>
                       Săn Deal Nhanh
                   </h2>
                   <DealHunter />
               </div>
            </section>
          </div>
        );
      case 'plan':
          return (
              <div className="space-y-6">
                  <h2 className="text-2xl font-bold text-gray-800 mb-2 flex items-center gap-3">
                      <div className="bg-blue-600 p-2 rounded-xl text-white shadow-lg shadow-blue-200">
                          <CalendarRange className="w-6 h-6" />
                      </div>
                      Kế hoạch mua sắm & Thanh toán
                  </h2>
                  <p className="text-gray-500">Tự động phân tích và đề xuất thẻ tốt nhất cho danh sách mua sắm và hóa đơn sắp tới.</p>
                  <ShoppingPlanner 
                    items={shoppingList}
                    upcomingBills={pendingBills}
                    onAddItem={handleAddItem}
                    onRemoveItem={handleRemoveItem}
                    onToggleItem={handleToggleItem}
                    cardUsage={cardUsage}
                  />
              </div>
          );
      case 'deals':
        return <DealHunter />;
      case 'cards':
        return <MyCards />;
      case 'calc':
        return <CardOptimizer cardUsage={cardUsage} />;
      case 'history':
        return (
            <div className="max-w-4xl mx-auto">
                <h2 className="text-2xl font-bold text-gray-800 mb-4">Lịch sử & Hóa đơn</h2>
                <SpendingManager 
                    transactions={transactions} 
                    onAddTransaction={handleAddTransaction} 
                    onRemoveTransaction={handleRemoveTransaction}
                    onEditTransaction={handleEditTransaction}
                    onClearAllTransactions={handleClearAllTransactions}
                    cardUsage={cardUsage}
                    financialEvents={computedFinancialEvents}
                    currentAsset={currentAsset}
                    onUpdateAsset={setCurrentAsset}
                    onAddEvent={handleAddEvent}
                    onRemoveEvent={handleRemoveEvent}
                    onToggleEvent={handleToggleEvent}
                />
            </div>
        );
      default:
        return <DealHunter />;
    }
  };

  return (
    <div className="min-h-screen bg-gray-50 flex flex-col md:flex-row">
      {/* Mobile Header */}
      <div className="md:hidden bg-white p-4 shadow-sm flex items-center justify-between sticky top-0 z-50">
        <div className="flex items-center gap-2">
           <div className="bg-shopee p-1.5 rounded-lg">
             <ShoppingBag className="w-5 h-5 text-white" />
           </div>
           <span className="font-bold text-lg text-shopee">ShopeeHunter</span>
        </div>
      </div>

      {/* Sidebar Navigation (Desktop) */}
      <aside className="hidden md:flex flex-col w-64 bg-white border-r border-gray-200 h-screen sticky top-0">
        <div className="p-6">
          <div className="flex items-center gap-3 mb-8">
            <div className="bg-shopee p-2 rounded-xl shadow-lg shadow-orange-200">
               <ShoppingBag className="w-6 h-6 text-white" />
            </div>
            <h1 className="text-xl font-bold text-gray-800 tracking-tight">Shopee<span className="text-shopee">Hunter</span></h1>
          </div>

          <nav className="space-y-2">
            <NavButton 
              active={activeTab === 'dashboard'} 
              onClick={() => setActiveTab('dashboard')} 
              icon={<LayoutDashboard size={20} />} 
              label="Tổng quan" 
            />
             <NavButton 
              active={activeTab === 'plan'} 
              onClick={() => setActiveTab('plan')} 
              icon={<CalendarRange size={20} />} 
              label="Kế hoạch mua sắm" 
            />
            <NavButton 
              active={activeTab === 'history'} 
              onClick={() => setActiveTab('history')} 
              icon={<Wallet size={20} />} 
              label="Chi tiêu & Hóa đơn" 
            />
            <NavButton 
              active={activeTab === 'deals'} 
              onClick={() => setActiveTab('deals')} 
              icon={<Flame size={20} />} 
              label="Săn Deal Hot" 
            />
            <NavButton 
              active={activeTab === 'calc'} 
              onClick={() => setActiveTab('calc')} 
              icon={<ShoppingBag size={20} />} 
              label="Tối ưu mua sắm" 
            />
            <NavButton 
              active={activeTab === 'cards'} 
              onClick={() => setActiveTab('cards')} 
              icon={<CreditCard size={20} />} 
              label="Ví thẻ của tôi" 
            />
          </nav>
        </div>
        
        <div className="mt-auto p-6 border-t border-gray-100">
           <div className="bg-orange-50 p-4 rounded-xl border border-orange-100">
              <p className="text-xs text-orange-800 font-semibold mb-1">Mẹo hôm nay</p>
              <p className="text-xs text-orange-600">Thanh toán điện nước qua Shopee bằng thẻ VPBank để nhận 6%!</p>
           </div>
        </div>
      </aside>

      {/* Main Content */}
      <main className="flex-1 p-4 md:p-8 overflow-y-auto">
        <div className="max-w-6xl mx-auto">
           {renderContent()}
        </div>
      </main>

      {/* Mobile Bottom Nav */}
      <nav className="md:hidden fixed bottom-0 left-0 right-0 bg-white border-t border-gray-200 flex justify-around p-3 z-50">
        <MobileNavBtn active={activeTab === 'dashboard'} onClick={() => setActiveTab('dashboard')} icon={<LayoutDashboard size={24} />} />
        <MobileNavBtn active={activeTab === 'plan'} onClick={() => setActiveTab('plan')} icon={<CalendarRange size={24} />} />
        <MobileNavBtn active={activeTab === 'deals'} onClick={() => setActiveTab('deals')} icon={<Flame size={24} />} />
        <MobileNavBtn active={activeTab === 'calc'} onClick={() => setActiveTab('calc')} icon={<ShoppingBag size={24} />} />
        <MobileNavBtn active={activeTab === 'cards'} onClick={() => setActiveTab('cards')} icon={<CreditCard size={24} />} />
      </nav>
    </div>
  );
};

const NavButton = ({ active, onClick, icon, label }: { active: boolean; onClick: () => void; icon: React.ReactNode; label: string }) => (
  <button
    onClick={onClick}
    className={`w-full flex items-center gap-3 px-4 py-3 rounded-xl transition-all font-medium ${
      active 
        ? 'bg-orange-50 text-shopee shadow-sm' 
        : 'text-gray-500 hover:bg-gray-50 hover:text-gray-800'
    }`}
  >
    {icon}
    <span>{label}</span>
  </button>
);

const MobileNavBtn = ({ active, onClick, icon }: { active: boolean; onClick: () => void; icon: React.ReactNode }) => (
  <button
    onClick={onClick}
    className={`p-2 rounded-lg transition-colors ${
      active ? 'text-shopee bg-orange-50' : 'text-gray-400'
    }`}
  >
    {icon}
  </button>
);

export default App;