
export interface CreditCard {
  id: string;
  name: string;
  bank: 'VPBank' | 'MSB' | 'Techcombank' | 'Cash';
  type: string;
  image: string; // Placeholder color or gradient
  cashbackRate: number; // Percentage, e.g., 6 for 6%
  maxCashback: number; // Max amount per month
  minSpend?: number; // Minimum spend to trigger
  category: 'All' | 'Online' | 'Shopee' | 'Specific' | 'Cash';
  notes: string;
  count: number; // Quantity of this card owned
  dueDate?: number; // Day of month (e.g., 5, 7, 8)
}

export interface Deal {
  id: string;
  title: string;
  description: string;
  price?: string;
  originalPrice?: string;
  discount?: string;
  link?: string;
  type: '1k' | '9k' | 'voucher' | 'flash_sale';
}

export interface OptimizationResult {
  cardId: string;
  cardName: string;
  cashbackAmount: number;
  finalPrice: number;
  reason: string;
  isMaxedOut?: boolean;
}

export interface ChatMessage {
  id: string;
  role: 'user' | 'model';
  text: string;
  deals?: Deal[];
  isThinking?: boolean;
}

export type TransactionCategory = 'Shopee' | 'Online' | 'Electricity' | 'Water' | 'Internet' | 'Phone' | 'Supermarket' | 'Market' | 'VPBankNEO' | 'Other';

export interface Transaction {
  id: string;
  date: string;
  title: string;
  amount: number;
  category: TransactionCategory;
  cardId: string;
  cashbackEarned: number;
  note?: string;
  isEssential?: boolean; // Đánh dấu khoản chi thiết yếu
}

export interface CardUsageStatus {
  cardId: string;
  totalSpent: number;
  totalCashback: number;
  remainingCap: number;
  minSpend: number;
  metMinSpend: boolean;
  remainingMinSpend: number;
}

export type FinancialEventType = 'income' | 'expense';

export interface FinancialEvent {
  id: string;
  title: string;
  amount: number;
  date: string; // YYYY-MM-DD
  type: FinancialEventType;
  isCompleted: boolean;
  recurring?: boolean;
  isAutoGenerated?: boolean; // To distinguish card bills from manual events
}

export interface ShoppingItem {
  id: string;
  name: string;
  estimatedPrice: number;
  category: TransactionCategory;
  plannedDate: string; // YYYY-MM-DD
  priority: 'High' | 'Medium' | 'Low';
  isPurchased: boolean;
}
